name: test_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dartz: ^0.10.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  intl: ^0.18.0
  fluttertoast: ^8.0.8
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    # - images/a_dot_ham.jpeg
